//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.ecc;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for QualificationElementType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QualificationElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Qualifiers" type="{https://uri.etsi.org/TrstSvc/SvcInfoExt/eSigDir-1999-93-EC-TrustedList/#}QualifiersType"/&gt;
 *         &lt;element name="CriteriaList" type="{https://uri.etsi.org/TrstSvc/SvcInfoExt/eSigDir-1999-93-EC-TrustedList/#}CriteriaListType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QualificationElementType", propOrder = { "qualifiers", "criteriaList" })
public class QualificationElementTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Qualifiers", required = true)
    protected QualifiersTypeV5 qualifiers;
    @XmlElement(name = "CriteriaList", required = true)
    protected CriteriaListTypeV5 criteriaList;

    /**
     * Gets the value of the qualifiers property.
     * 
     * @return possible object is {@link QualifiersTypeV5 }
     * 
     */
    public QualifiersTypeV5 getQualifiers() {
        return qualifiers;
    }

    /**
     * Sets the value of the qualifiers property.
     * 
     * @param value
     *            allowed object is {@link QualifiersTypeV5 }
     * 
     */
    public void setQualifiers(QualifiersTypeV5 value) {
        this.qualifiers = value;
    }

    /**
     * Gets the value of the criteriaList property.
     * 
     * @return possible object is {@link CriteriaListTypeV5 }
     * 
     */
    public CriteriaListTypeV5 getCriteriaList() {
        return criteriaList;
    }

    /**
     * Sets the value of the criteriaList property.
     * 
     * @param value
     *            allowed object is {@link CriteriaListTypeV5 }
     * 
     */
    public void setCriteriaList(CriteriaListTypeV5 value) {
        this.criteriaList = value;
    }

}
