package eu.europa.ec.joinup.tsl.model.enums;

public enum AuditTarget {

    NOTIFICATION, DRAFT_TL, PROD_TL, ADMINISTRATION_USER, ADMINISTRATION_PROPERTIES, ADMINISTRATION_LIST_SIGNING_CERT, ADMINISTRATION_CHECKS, CONTACT_LIST, JOBS, CACHE, NEW_TL, NEW_NOTIFICATION, NOTIFICATION_INTEGRATED, NEW_SIGNING_CERTIFICATE, UNAVAILABILITY, TL_STATUS_BREAK, SIGNATURE_INVALID, RETENTION_POLICY, DRAFTSTORE, USER

}
