package eu.europa.ec.joinup.tsl.model.enums;

public enum AuditAction {

    CREATE, UPDATE, DELETE, VALIDATION, CHECKCONFORMANCE, CHECKSIGNATURE, SEAL, SIGN, ARCHIVE, EXECUTE, DATABASE, ALERTING, EXPORT, LOGIN, LOAD_TL, RETENTION, SIGNATURE_ALERTING, TL_BREAK_ALERTING
}
