//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.tsl;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OtherTSLPointerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OtherTSLPointerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://uri.etsi.org/02231/v2#}ServiceDigitalIdentities" minOccurs="0"/&gt;
 *         &lt;element name="TSLLocation" type="{https://uri.etsi.org/02231/v2#}NonEmptyURIType"/&gt;
 *         &lt;element ref="{https://uri.etsi.org/02231/v2#}AdditionalInformation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OtherTSLPointerType", propOrder = { "serviceDigitalIdentities", "tslLocation", "additionalInformation" })
public class OtherTSLPointerTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ServiceDigitalIdentities")
    protected ServiceDigitalIdentityListTypeV5 serviceDigitalIdentities;
    @XmlElement(name = "TSLLocation", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String tslLocation;
    @XmlElement(name = "AdditionalInformation")
    protected AdditionalInformationTypeV5 additionalInformation;

    /**
     * Gets the value of the serviceDigitalIdentities property.
     * 
     * @return possible object is {@link ServiceDigitalIdentityListTypeV5 }
     * 
     */
    public ServiceDigitalIdentityListTypeV5 getServiceDigitalIdentities() {
        return serviceDigitalIdentities;
    }

    /**
     * Sets the value of the serviceDigitalIdentities property.
     * 
     * @param value
     *            allowed object is {@link ServiceDigitalIdentityListTypeV5 }
     * 
     */
    public void setServiceDigitalIdentities(ServiceDigitalIdentityListTypeV5 value) {
        this.serviceDigitalIdentities = value;
    }

    /**
     * Gets the value of the tslLocation property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTSLLocation() {
        return tslLocation;
    }

    /**
     * Sets the value of the tslLocation property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTSLLocation(String value) {
        this.tslLocation = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return possible object is {@link AdditionalInformationTypeV5 }
     * 
     */
    public AdditionalInformationTypeV5 getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *            allowed object is {@link AdditionalInformationTypeV5 }
     * 
     */
    public void setAdditionalInformation(AdditionalInformationTypeV5 value) {
        this.additionalInformation = value;
    }

}
