//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.tsl;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TSPServiceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TSPServiceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{https://uri.etsi.org/02231/v2#}ServiceInformation"/&gt;
 *         &lt;element ref="{https://uri.etsi.org/02231/v2#}ServiceHistory" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TSPServiceType", propOrder = { "serviceInformation", "serviceHistory" })
public class TSPServiceTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ServiceInformation", required = true)
    protected TSPServiceInformationTypeV5 serviceInformation;
    @XmlElement(name = "ServiceHistory")
    protected ServiceHistoryTypeV5 serviceHistory;

    /**
     * Gets the value of the serviceInformation property.
     * 
     * @return possible object is {@link TSPServiceInformationTypeV5 }
     * 
     */
    public TSPServiceInformationTypeV5 getServiceInformation() {
        return serviceInformation;
    }

    /**
     * Sets the value of the serviceInformation property.
     * 
     * @param value
     *            allowed object is {@link TSPServiceInformationTypeV5 }
     * 
     */
    public void setServiceInformation(TSPServiceInformationTypeV5 value) {
        this.serviceInformation = value;
    }

    /**
     * Gets the value of the serviceHistory property.
     * 
     * @return possible object is {@link ServiceHistoryTypeV5 }
     * 
     */
    public ServiceHistoryTypeV5 getServiceHistory() {
        return serviceHistory;
    }

    /**
     * Sets the value of the serviceHistory property.
     * 
     * @param value
     *            allowed object is {@link ServiceHistoryTypeV5 }
     * 
     */
    public void setServiceHistory(ServiceHistoryTypeV5 value) {
        this.serviceHistory = value;
    }

}
