//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.xades;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OCSPRefType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OCSPRefType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OCSPIdentifier" type="{https://uri.etsi.org/01903/v1.3.2#}OCSPIdentifierType"/&gt;
 *         &lt;element name="DigestAlgAndValue" type="{https://uri.etsi.org/01903/v1.3.2#}DigestAlgAndValueType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OCSPRefType", propOrder = { "ocspIdentifier", "digestAlgAndValue" })
public class OCSPRefTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "OCSPIdentifier", required = true)
    protected OCSPIdentifierTypeV5 ocspIdentifier;
    @XmlElement(name = "DigestAlgAndValue")
    protected DigestAlgAndValueTypeV5 digestAlgAndValue;

    /**
     * Gets the value of the ocspIdentifier property.
     * 
     * @return possible object is {@link OCSPIdentifierTypeV5 }
     * 
     */
    public OCSPIdentifierTypeV5 getOCSPIdentifier() {
        return ocspIdentifier;
    }

    /**
     * Sets the value of the ocspIdentifier property.
     * 
     * @param value
     *            allowed object is {@link OCSPIdentifierTypeV5 }
     * 
     */
    public void setOCSPIdentifier(OCSPIdentifierTypeV5 value) {
        this.ocspIdentifier = value;
    }

    /**
     * Gets the value of the digestAlgAndValue property.
     * 
     * @return possible object is {@link DigestAlgAndValueTypeV5 }
     * 
     */
    public DigestAlgAndValueTypeV5 getDigestAlgAndValue() {
        return digestAlgAndValue;
    }

    /**
     * Sets the value of the digestAlgAndValue property.
     * 
     * @param value
     *            allowed object is {@link DigestAlgAndValueTypeV5 }
     * 
     */
    public void setDigestAlgAndValue(DigestAlgAndValueTypeV5 value) {
        this.digestAlgAndValue = value;
    }

}
