//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.01.06 at 08:00:20 AM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://uri.etsi.org/01903/v1.3.2#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapters({
        @javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(value = eu.europa.esig.jaxb.v5.utils.JaxbGregorianCalendarZulu.class, type = javax.xml.datatype.XMLGregorianCalendar.class) })
package eu.europa.esig.jaxb.v5.xades;
