//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.xades;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SignerRoleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignerRoleType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClaimedRoles" type="{https://uri.etsi.org/01903/v1.3.2#}ClaimedRolesListType" minOccurs="0"/&gt;
 *         &lt;element name="CertifiedRoles" type="{https://uri.etsi.org/01903/v1.3.2#}CertifiedRolesListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignerRoleType", propOrder = { "claimedRoles", "certifiedRoles" })
public class SignerRoleTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ClaimedRoles")
    protected ClaimedRolesListTypeV5 claimedRoles;
    @XmlElement(name = "CertifiedRoles")
    protected CertifiedRolesListTypeV5 certifiedRoles;

    /**
     * Gets the value of the claimedRoles property.
     * 
     * @return possible object is {@link ClaimedRolesListTypeV5 }
     * 
     */
    public ClaimedRolesListTypeV5 getClaimedRoles() {
        return claimedRoles;
    }

    /**
     * Sets the value of the claimedRoles property.
     * 
     * @param value
     *            allowed object is {@link ClaimedRolesListTypeV5 }
     * 
     */
    public void setClaimedRoles(ClaimedRolesListTypeV5 value) {
        this.claimedRoles = value;
    }

    /**
     * Gets the value of the certifiedRoles property.
     * 
     * @return possible object is {@link CertifiedRolesListTypeV5 }
     * 
     */
    public CertifiedRolesListTypeV5 getCertifiedRoles() {
        return certifiedRoles;
    }

    /**
     * Sets the value of the certifiedRoles property.
     * 
     * @param value
     *            allowed object is {@link CertifiedRolesListTypeV5 }
     * 
     */
    public void setCertifiedRoles(CertifiedRolesListTypeV5 value) {
        this.certifiedRoles = value;
    }

}
