//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 08:00:20 AM CET 
//

package eu.europa.esig.jaxb.v5.xades;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.europa.esig.jaxb.v5.xmldsig.TransformsTypeV5;

/**
 * <p>
 * Java class for SignaturePolicyIdType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignaturePolicyIdType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SigPolicyId" type="{https://uri.etsi.org/01903/v1.3.2#}ObjectIdentifierType"/&gt;
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Transforms" minOccurs="0"/&gt;
 *         &lt;element name="SigPolicyHash" type="{https://uri.etsi.org/01903/v1.3.2#}DigestAlgAndValueType"/&gt;
 *         &lt;element name="SigPolicyQualifiers" type="{https://uri.etsi.org/01903/v1.3.2#}SigPolicyQualifiersListType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignaturePolicyIdType", propOrder = { "sigPolicyId", "transforms", "sigPolicyHash", "sigPolicyQualifiers" })
public class SignaturePolicyIdTypeV5 implements Serializable {

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SigPolicyId", required = true)
    protected ObjectIdentifierTypeV5 sigPolicyId;
    @XmlElement(name = "Transforms", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected TransformsTypeV5 transforms;
    @XmlElement(name = "SigPolicyHash", required = true)
    protected DigestAlgAndValueTypeV5 sigPolicyHash;
    @XmlElement(name = "SigPolicyQualifiers")
    protected SigPolicyQualifiersListTypeV5 sigPolicyQualifiers;

    /**
     * Gets the value of the sigPolicyId property.
     * 
     * @return possible object is {@link ObjectIdentifierTypeV5 }
     * 
     */
    public ObjectIdentifierTypeV5 getSigPolicyId() {
        return sigPolicyId;
    }

    /**
     * Sets the value of the sigPolicyId property.
     * 
     * @param value
     *            allowed object is {@link ObjectIdentifierTypeV5 }
     * 
     */
    public void setSigPolicyId(ObjectIdentifierTypeV5 value) {
        this.sigPolicyId = value;
    }

    /**
     * Gets the value of the transforms property.
     * 
     * @return possible object is {@link TransformsTypeV5 }
     * 
     */
    public TransformsTypeV5 getTransforms() {
        return transforms;
    }

    /**
     * Sets the value of the transforms property.
     * 
     * @param value
     *            allowed object is {@link TransformsTypeV5 }
     * 
     */
    public void setTransforms(TransformsTypeV5 value) {
        this.transforms = value;
    }

    /**
     * Gets the value of the sigPolicyHash property.
     * 
     * @return possible object is {@link DigestAlgAndValueTypeV5 }
     * 
     */
    public DigestAlgAndValueTypeV5 getSigPolicyHash() {
        return sigPolicyHash;
    }

    /**
     * Sets the value of the sigPolicyHash property.
     * 
     * @param value
     *            allowed object is {@link DigestAlgAndValueTypeV5 }
     * 
     */
    public void setSigPolicyHash(DigestAlgAndValueTypeV5 value) {
        this.sigPolicyHash = value;
    }

    /**
     * Gets the value of the sigPolicyQualifiers property.
     * 
     * @return possible object is {@link SigPolicyQualifiersListTypeV5 }
     * 
     */
    public SigPolicyQualifiersListTypeV5 getSigPolicyQualifiers() {
        return sigPolicyQualifiers;
    }

    /**
     * Sets the value of the sigPolicyQualifiers property.
     * 
     * @param value
     *            allowed object is {@link SigPolicyQualifiersListTypeV5 }
     * 
     */
    public void setSigPolicyQualifiers(SigPolicyQualifiersListTypeV5 value) {
        this.sigPolicyQualifiers = value;
    }

}
